### ISSUE TITLE
Shadowlist is not scrolling

### ISSUE THREAD

**Issue by Rohit3523** [azimgd/shadowlist#2]
I tried the example code and shadowlist is not scrolling but it is working fine for flatlist and flashlist

React Native Version: 0.74.0

**Comment by azimgd** [comment]
Could you make sure ShadowListContainer occupies fixed height (e.g. full viewport) this could be adjusted in the same way as you do on FlatList via `contentContainerStyle`.

**Comment by azimgd** [comment]
Additionally you could find a demo showcasing the functionality [here](https://github.com/azimgd/shadowlist/blob/main/example/src/App.tsx). Please send me a reproducible snippet so I can provide you a better assistance. Thanks!

**Comment by RohitBansal272** [comment]
I have used the same code (did copy and paste) from the example directory

**Comment by azimgd** [comment]
Interesting, would you mind installing `v0.0.2` and try again please?

**Comment by Rohit3523** [comment]
Still same issue

**Comment by Rohit3523** [comment]
Just noticed when i click on "Load more" button, it gives me react error (i have attached the image)
![Screenshot_1715809617](https://github.com/azimgd/shadowlist/assets/40559587/c91f86e1-5820-4903-a24b-f80e889e62d5)

**Comment by azimgd** [comment]
Thanks for the report, let me check.

**Comment by Rohit3523** [comment]
I will be available after 6 hours to test it again. Take your time to find and fix it :)

**Comment by azimgd** [comment]
Missed that you are running it on Android, which is currently [not supported](https://www.reddit.com/r/reactnative/comments/1cspfm5/shadowlist_a_new_rn_component_for_improved_list/). I expect to have it done within couple weeks. Thanks!
