### ISSUE TITLE
Multi item layout 

### ISSUE THREAD

**Issue by Nadimkhan120** [azimgd/shadowlist#4]
hi @azimgd  thanks for your effort for this project

I have a question to ask
 
Does this list support different height item, i have a screen when i need to show a header height of 50, a horizontal carousal, a section of some categories,  then a horizontal list of items,

Earlier i used flashlist and flatlist but these are not working so well on android devices and scroll is laggay

**Comment by azimgd** [comment]
Hey, thanks for checking this out.

> Does this list support different height item

That's where this library excels!

> i have a screen when i need to show a header height of 50, a horizontal carousal, a section of some categories, then a horizontal list of items

You can definitely nest lists, both horizontal and vertical, and everything should work right out of the box.

> Earlier i used flashlist and flatlist but these are not working so well on android devices and scroll is laggay

Both FlatList and FlashList have noticeable performance drawbacks. However, ShadowList currently works only on iOS. Check back within a week or two for the Android version.
